title: Hemlock Productions
author: Cid Music
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Find my music here, also my work with other bands and more awesome stuff. 
  It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
